### ISSUE TITLE
Decimal values in alteration frequencies are not supported

### ISSUE THREAD

**Issue by schultzn** [iVis-at-Bilkent/TCGA-Curation-Tool#36]
Need to support decimal values -- suggest to support files with decimals and round to the nearest integer

Special case: values under 0
    Under data view settings, we could allow users to decide on thresholds

**Comment by ugurdogrusoz** [comment]
@schultzn What do you mean by special case: values under 0? When we have negative numbers we display them with white-blue scale.

Let's make necessary changes  
- to be able to read numbers with decimals from the data file and round them to the nearest integer when displaying
- to let users specify threshold values where below a certain value is ignored (same as 0) and above a certain threshold value is ignored (same as 100). @schultzn Should we have a second pair of values for negative values (e.g. 10, 90 and -5, -95)?
- to let users choose between a few different functions for color coding (linear vs non-linear ones; see here: http://easings.net/) values between these thresholds.

**Comment by schultzn** [comment]
Sorry, meant values between 0 and 1. I guess anything above 0.5 we can round up to one. The values between 0 and 0.5 are either 0% or can be shown as < 0.5%.

**Comment by istemi-bahceci** [comment]
- Decimal values are rounded to nearest integers, the values between 0 and 0.5 are represented as <0.5.

- I have used a logarithmic mapping function instead of linear function to map alteration frequencies to the associated red and blue colors. Currently, colors change more dramatically according to the alterations compared to the linear mapping. 

For testing you can use following genomic data file: [sampleGenomicData3.txt](https://github.com/iVis-at-Bilkent/TCGA-Curation-Tool/files/461398/sampleGenomicData3.txt)

**Comment by ugurdogrusoz** [comment]
It doesn't look like they are being "rounded" though. 3.4 is shown as 4, not 3.

**Comment by istemi-bahceci** [comment]
Fixed that part also.
